import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/context/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f2f0ed',
        'secondary-container': '#f7decc',
        'on-primary-fixed': '#281810',
        'primary-fixed': '#fbdcce',
        'primary': '#25160e',
        'on-secondary-fixed-variant': '#544437',
        'surface-container-low': '#f5f3ef',
        'secondary-fixed': '#f7decc',
        'surface-dim': '#dbdad6',
        'error': '#ba1a1a',
        'tertiary': '#0b1d11',
        'on-tertiary-fixed': '#0e1f13',
        'background': '#fbf9f5',
        'secondary': '#6d5b4d',
        'on-background': '#1b1c1a',
        'on-primary-fixed-variant': '#574238',
        'tertiary-fixed': '#d3e8d5',
        'inverse-surface': '#30312e',
        'tertiary-fixed-dim': '#b7ccb9',
        'surface-container-highest': '#e4e2de',
        'surface-bright': '#fbf9f5',
        'surface-tint': '#705a4f',
        'surface-variant': '#e4e2de',
        'on-surface-variant': '#4f4540',
        'on-secondary-container': '#736153',
        'on-tertiary-container': '#869b89',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#dec1b3',
        'surface-container-high': '#eae8e4',
        'surface': '#fbf9f5',
        'on-tertiary-fixed-variant': '#394b3d',
        'outline-variant': '#d3c3bd',
        'tertiary-container': '#203225',
        'outline': '#81756f',
        'surface-container': '#efeeea',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-surface': '#1b1c1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-primary-container': '#aa9084',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#d9c2b1',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#3c2a21',
        'on-secondary-fixed': '#25190e',
        'inverse-primary': '#dec1b3',
      },
      fontFamily: {
        'caslon': ['Libre Caslon Text', 'Georgia', 'serif'],
        'sans-dm': ['DM Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'gutter': '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container': '1280px',
      },
      backdropBlur: {
        xs: '4px',
      },
      boxShadow: {
        'roasted': '0 10px 25px -5px rgba(60,42,33,0.08), 0 8px 10px -6px rgba(60,42,33,0.04)',
        'roasted-lg': '0 20px 40px -10px rgba(60,42,33,0.12), 0 10px 20px -8px rgba(60,42,33,0.06)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
